[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ssfpy"
version = "2025.0.0"
dependencies = [
  "antspyx==0.6.1", # works also for Apple Silicon (precompiled binaries do exist)
]
requires-python = ">=3.12" # for antspyx = 0.6.1
authors = [
  {name = "Benoît Béranger", email = "benoit.beranger@icm-institute.org"},
]
maintainers = [
  {name = "Benoît Béranger", email = "benoit.beranger@icm-institute.org"},
]
description = "SSFP processing pipelines"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]
keywords = ["MRI", "SSFP", "bSFFP", "processing", "python"]
classifiers = [
  "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage      = "https://github.com/benoitberanger/ssfpy"
Repository    = "https://github.com/benoitberanger/ssfpy"
"Bug Tracker" = "https://github.com/benoitberanger/ssfpy/issues"
